### ISSUE TITLE
Write a fully fleshed-out README for the repository.

### ISSUE THREAD

**Issue by khipkin** [rit-csc/CSCWebsite#6]
"TODO" is unprofessional and uninformative.

**Comment by chrissprague** [comment]
bumping this up to critical importance because it should be done sooner rather than later

what will be in the README? Perhaps instructions to clone a copy and work on it for yourself (obviously we aren't obligated how to explain the `git` steps involved in any depth, but more like any custom setup steps specific to the CSC site involved in getting it up and running in the first place... `settings.py`, etc.)

**Comment by khipkin** [comment]
Resolved in pull request #21.
