### ISSUE TITLE
Requests?

### ISSUE THREAD

**Issue by RaineForest** [rit-csc/CSCWebsite#8]
@khipkin https://github.com/rit-csc/CSCWebsite/blob/github_api/csc_new/pages/views.py#L54 Why is the requests package necessary when both [json](https://docs.python.org/3.4/library/json.html) and [urllib](https://docs.python.org/3/library/urllib.html) are python builtins?

**Comment by khipkin** [comment]
@RaineForest, I don't know. This is my first vaguely-successful attempt to use an API.  Are you saying the same thing can be done with python built-in libraries?

**Comment by ritcsc** [comment]
Yes

**Comment by chrissprague** [comment]
I don't think this should be filed as an issue per se, because it seems to be commentary on code that hasn't even been merged into live yet. Not saying that this one should be removed but for future occurrences like this, that's my opinion. Agree/disagree?

Better yet, is there a way to limit the scope of a filed issue to a specific branch?

**Comment by khipkin** [comment]
@chrissprague @RaineForest Even if it isn't on the live site or the primary branch, it's still an "issue" with the codebase that Dakota felt should be addressed.  Now that I know everything mentioned above, I also agree that it is an issue.  I will fix it ASAP.

**Comment by khipkin** [comment]
Fixed as of e91e7d425df425588daeb6b2165b74149b328d41.
